version: 0.2

env:
  shell: bash
  variables:
    APPSPEC_FOLDER: codedeploy_appspec
    APPSPEC_FILE_NAME: bundle.zip
    DEPLOY_ACTION_INPUT_FOLDER: deploy_action_input
phases:
  build:
    on-failure: ABORT
    commands:
      - ./$DEPLOY_ACTION_INPUT_FOLDER/scripts/create_deployment.sh



