version: 0.0
os: linux
files:
  - source: SimpleWeb
    destination: /var/www/html
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 600
    - location: scripts/generate_hostname.sh
      timeout: 10
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
