version: 0.0
os: linux
files:
  - source: SimpleWeb
    destination: /var/www/html
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 600
    - location: scripts/generate_child_pages.sh
      timeout: 10
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
  BeforeAllowTraffic:
    - location: scripts/time_gate.sh
      timeout: 3600
